<?php

require_once 'om/BaseLabel.php';


/**
 * Skeleton subclass for representing a row from the 'label' table.
 *
 * Language based labels
 *
 * This class was autogenerated by Propel on:
 *
 * Thu Dec 13 22:27:35 2007
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    
 */
class Label extends BaseLabel {

} // Label
