<?php

  // include base peer class
  require_once 'om/BaseNagiosServiceCheckCommandParameterPeer.php';

  // include object class
  include_once 'NagiosServiceCheckCommandParameter.php';


/**
 * Skeleton subclass for performing query and update operations on the 'nagios_service_check_command_parameter' table.
 *
 * Parameter for check command for service or service template
 *
 * This class was autogenerated by Propel on:
 *
 * Thu Dec 13 21:25:24 2007
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    
 */
class NagiosServiceCheckCommandParameterPeer extends BaseNagiosServiceCheckCommandParameterPeer {

} // NagiosServiceCheckCommandParameterPeer
