<?php

  // include base peer class
  require_once 'om/BaseNagiosContactGroupPeer.php';

  // include object class
  include_once 'NagiosContactGroup.php';


/**
 * Skeleton subclass for performing query and update operations on the 'nagios_contact_group' table.
 *
 * Nagios Contact Group
 *
 * This class was autogenerated by Propel on:
 *
 * Thu Dec 13 21:25:24 2007
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    
 */
class NagiosContactGroupPeer extends BaseNagiosContactGroupPeer {

    public function getByName($name) {
     $c = new Criteria();
     $c->add(NagiosContactGroupPeer::NAME, $name);
     $c->setIgnoreCase(true);
     $contactgroup = NagiosContactGroupPeer::doSelectOne($c);
     if(!$contactgroup)
      return false;
     return $contactgroup;
    }

} // NagiosContactGroupPeer
