<?php

  // include base peer class
  require_once 'om/BaseNagiosEscalationPeer.php';

  // include object class
  include_once 'NagiosEscalation.php';


/**
 * Skeleton subclass for performing query and update operations on the 'nagios_escalation' table.
 *
 * Nagios Escalation
 *
 * This class was autogenerated by Propel on:
 *
 * Thu Dec 13 21:25:24 2007
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    
 */
class NagiosEscalationPeer extends BaseNagiosEscalationPeer {

} // NagiosEscalationPeer
