<?php

  // include base peer class
  require_once 'om/BaseNagiosHostgroupPeer.php';

  // include object class
  include_once 'NagiosHostgroup.php';


/**
 * Skeleton subclass for performing query and update operations on the 'nagios_hostgroup' table.
 *
 * Nagios Hostgroup
 *
 * This class was autogenerated by Propel on:
 *
 * Thu Dec 13 21:25:24 2007
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    
 */
class NagiosHostgroupPeer extends BaseNagiosHostgroupPeer {

    public function getByName($name) {
     $c = new Criteria();
     $c->add(NagiosHostgroupPeer::NAME, $name);
     $c->setIgnoreCase(true);
     $hostgroup = NagiosHostgroupPeer::doSelectOne($c);
     if(!$hostgroup)
      return false;
     return $hostgroup;
    }

} // NagiosHostgroupPeer
