<?php

  // include base peer class
  require_once 'om/BaseNagiosServiceTemplatePeer.php';

  // include object class
  include_once 'NagiosServiceTemplate.php';


/**
 * Skeleton subclass for performing query and update operations on the 'nagios_service_template' table.
 *
 * Nagios Service Template
 *
 * This class was autogenerated by Propel on:
 *
 * Thu Dec 13 21:25:24 2007
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    
 */
class NagiosServiceTemplatePeer extends BaseNagiosServiceTemplatePeer {
    public function getByName($name) {
        $c = new Criteria();
        $c->add(NagiosServiceTemplatePeer::NAME, $name);
        $c->setIgnoreCase(true);
        $template = NagiosServiceTemplatePeer::doSelectOne($c);
        if(!$template) {
         return false;
        }
        return $template;
    }

} // NagiosServiceTemplatePeer
