<?php

  // include base peer class
  require_once 'om/BaseNagiosContactAddressPeer.php';

  // include object class
  include_once 'NagiosContactAddress.php';


/**
 * Skeleton subclass for performing query and update operations on the 'nagios_contact_address' table.
 *
 * Nagios Contact Address
 *
 * This class was autogenerated by Propel on:
 *
 * Thu Dec 13 21:25:24 2007
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    
 */
class NagiosContactAddressPeer extends BaseNagiosContactAddressPeer {

} // NagiosContactAddressPeer
