<?php

  // include base peer class
  require_once 'om/BaseNagiosContactGroupMemberPeer.php';

  // include object class
  include_once 'NagiosContactGroupMember.php';


/**
 * Skeleton subclass for performing query and update operations on the 'nagios_contact_group_member' table.
 *
 * Member of a Nagios Contact Group
 *
 * This class was autogenerated by Propel on:
 *
 * Thu Dec 13 21:25:24 2007
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    
 */
class NagiosContactGroupMemberPeer extends BaseNagiosContactGroupMemberPeer {

} // NagiosContactGroupMemberPeer
