<?php

require_once 'om/BaseNagiosServiceGroupMember.php';


/**
 * Skeleton subclass for representing a row from the 'nagios_service_group_member' table.
 *
 * 
 *
 * This class was autogenerated by Propel on:
 *
 * Thu Dec 13 21:25:24 2007
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    
 */
class NagiosServiceGroupMember extends BaseNagiosServiceGroupMember {

} // NagiosServiceGroupMember
